//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string typeOfClothing { get; set; }
        public string decorFirst { get; set; }
        public string decorSecond { get; set; }
        public string decorThird { get; set; }
        public string orderLogin { get; set; }
        public int idOrder { get; set; }
    
        public virtual User User { get; set; }
    }
}
